//Package services generated by service-enroll-generate.go;
// !DO NOT EDIT THIS FILE!
package service

import (
	
	"backend/serve/authmgmt" //auth-mgmt ,  auth, , 111111@qq.com
	"backend/serve/chat" //chat-mgmt ,  chat, , 1637901557@qq.com
	"backend/serve/file" //file-mgmt ,  file, , 1637901557@qq.com
	"backend/serve/fileService" //file-mgmt ,  fileService, , 1637901557@qq.com
	"backend/serve/test" //file-mgmt ,  fileService, , 1637901557@qq.com
	"backend/serve/user" //user-mgmt ,  user, , 1637901557@qq.com
)

//Enroll will be called from serve cmd
func Enroll(){
  
  authmgmt.Enroll(`{"name":"auth","email":"111111@qq.com"}`)
  chat.Enroll(`{"name":"chat","email":"1637901557@qq.com"}`)
  file.Enroll(`{"name":"file","email":"1637901557@qq.com"}`)
  fileService.Enroll(`{"name":"fileService","email":"1637901557@qq.com"}`)
  test.Enroll(`{"name":"fileService","email":"1637901557@qq.com"}`)
  user.Enroll(`{"name":"user","email":"1637901557@qq.com"}`)
}
